pages/urls.py
# pages/urls.py

from xml.etree.ElementInclude import include
from django.urls import path, include
from .views import HomePageView, AboutPageView
from posts.views import  BoardView
from django.contrib import admin

urlpatterns = [path("about/", AboutPageView.as_view(), name="about"),
                path("", HomePageView.as_view(), name="home"),
                path("", include("posts.urls"))
            ]

posts/urls.py
from django.urls import path 
from posts.views import BoardView
urlpatterns = [path("", BoardView.as_view(), name="posts"),]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls),
            path("", include("pages.urls")),
            path("posts/", include("posts.urls")),
            ]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50] #This limit the characters to 50

pages/views.py
from cgitb import html
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

#def homePageView(request):
#    return HttpResponse("Hello, World!")

from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name= "home.html"

class AboutPageView(TemplateView):
    template_name: str="about.html"

posts/views.py
import imp
from re import template
from django.shortcuts import render

# Create your views here.
from .models import Post
from django.views.generic import ListView

class BoardView(ListView):
    model=Post
    template_name="posts.html"
    

templates/about.html
<!--templates/about.html-->
{% extends "base.html" %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/base.html
<!-- templates/base.html -->
<header>
    <a href="{% url 'home' %}">Home</a> |
    <a href="{% url 'about' %}">About</a> |
    <a href="{% url 'posts' %}">Posts</a>
</header>

{% block content %} {% endblock content %}

templates/home.html
<!-- templates/home.html -->

{% extends "base.html" %}

{% block content %}
<h1>Homepage</h1>
{% endblock content %}

templates/posts.html
<!-- templates/posts.html -->
{% extends "base.html" %}

{% block content %}
<h1>Message board homepage</h1> <ul>
    {% for post in post_list %} <li>{{ post.text }}</li>
    {% endfor %} </ul>
{% endblock content %}